# Generated by Django 5.0.4 on 2024-05-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='grupo_de_acesso',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('CDE', 'Cadastro Externo'), ('CDA', 'Cadastro Atividade'), ('CDI', 'Cadastro Inscrição'), ('LDP', 'Listagem de Pessoas')], max_length=3),
        ),
    ]
