# Generated by Django 5.0.4 on 2024-05-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_alter_users_grupo_de_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='tipoUsuario',
            field=models.CharField(choices=[('Funcionario', 'Funcionario'), ('Administrador', 'Administrador')], default='Indefinido', max_length=20),
        ),
    ]
