# Generated by Django 5.0.4 on 2024-05-28 01:41

import cadastro.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0005_users_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='funcao',
            field=models.CharField(default='Indefinido', max_length=30, validators=[cadastro.validator.validate_nome], verbose_name='Função'),
        ),
    ]
