# Generated by Django 5.0.4 on 2024-05-03 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atividade', models.CharField(choices=[('SV', 'Serviço'), ('CLS', 'Aula')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Externo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('nascimento', models.DateField()),
                ('responsavel_nome', models.CharField(max_length=50)),
                ('responsavel_cpf', models.DateField()),
                ('telefone', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=80)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_atividade', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('status', models.BooleanField()),
                ('tipo_atividade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.tipo_atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Inscrever_na_Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.atividade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.usuario_externo')),
            ],
        ),
    ]
