# Generated by Django 5.0.4 on 2024-06-09 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_superuser': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atividade',
            name='dia_atividade',
            field=models.ManyToManyField(to='cadastro.diaatividade'),
        ),
        migrations.AddField(
            model_name='inscrever_na_atividade',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.atividade'),
        ),
        migrations.AddField(
            model_name='lista_precenca',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.inscrever_na_atividade'),
        ),
        migrations.AddField(
            model_name='servico',
            name='responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_superuser': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserService', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscrever_na_atividade',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.usuario_externo'),
        ),
    ]
