# Generated by Django 5.0.4 on 2024-06-10 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista_precenca',
            name='aluno',
        ),
        migrations.CreateModel(
            name='Inscrever_Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_aula', models.TimeField(verbose_name='Hora da Aula')),
                ('nome_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.usuario_externo', verbose_name='Nome do aluno')),
                ('nome_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.atividade', verbose_name='Nome da Atividade')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Inscrever_na_Atividade',
        ),
        migrations.DeleteModel(
            name='lista_precenca',
        ),
    ]
