# Generated by Django 5.0.4 on 2024-06-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='hora_intervarlo',
            new_name='hora_intervalo',
        ),
    ]
