# Generated by Django 5.0.4 on 2024-06-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_inscrever_servico_dia_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrever_servico',
            name='dia_servico',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='inscrever_servico',
            name='hora_servico',
            field=models.CharField(max_length=4, verbose_name='Hora do Servico'),
        ),
    ]
