# Generated by Django 5.0.4 on 2024-05-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_usuario_externo_responsavel_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_atividade',
            name='tipo_atividade',
            field=models.CharField(choices=[('SV', 'Serviço'), ('CLS', 'Aula')], max_length=5),
        ),
    ]
