# Generated by Django 5.0.4 on 2024-05-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_tipo_atividade_tipo_atividade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='tipo_atividade',
        ),
        migrations.AddField(
            model_name='atividade',
            name='tipo_atividade',
            field=models.ManyToManyField(to='cadastro.tipo_atividade'),
        ),
    ]
