# Generated by Django 5.0.4 on 2024-05-03 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_remove_atividade_tipo_atividade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='tipo_atividade',
        ),
        migrations.AddField(
            model_name='atividade',
            name='tipo_atividade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.tipo_atividade'),
        ),
    ]
