# Generated by Django 5.0.4 on 2024-05-29 22:55

import cadastro.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_usuario_externo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='nome_atividade',
            field=models.CharField(max_length=50, unique=True, validators=[cadastro.validator.validate_nome]),
        ),
    ]
