# Generated by Django 5.0.4 on 2024-06-12 05:11

import cadastro.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_alter_usuario_externo_responsavel_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_externo',
            name='endereco',
            field=models.CharField(max_length=80, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='usuario_externo',
            name='responsavel_cpf',
            field=models.CharField(blank=True, default='Vazio', max_length=14, null=True, validators=[cadastro.validator.validate_cpf], verbose_name='CPF do Responsavel'),
        ),
        migrations.AlterField(
            model_name='usuario_externo',
            name='responsavel_nome',
            field=models.CharField(blank=True, default='Vazio', max_length=50, null=True, validators=[cadastro.validator.validate_nome], verbose_name='Nome do Responsavel'),
        ),
    ]
