# Generated by Django 5.0.4 on 2024-05-15 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_atividade_responsavel_lista_precenca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividade',
            old_name='status',
            new_name='Ativo',
        ),
    ]
