# Generated by Django 5.0.4 on 2024-05-16 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_alter_atividade_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista_precenca',
            name='atividade',
        ),
        migrations.AlterField(
            model_name='lista_precenca',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.inscrever_na_atividade'),
        ),
    ]
