# Generated by Django 5.0.4 on 2024-05-17 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_remove_lista_precenca_atividade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_precenca',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.usuario_externo'),
        ),
    ]
