# Generated by Django 5.0.4 on 2024-05-17 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_alter_lista_precenca_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_precenca',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.inscrever_na_atividade'),
        ),
    ]
