# Generated by Django 5.0.4 on 2024-05-19 01:36

import cadastro.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_alter_lista_precenca_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_externo',
            name='nome',
            field=models.CharField(max_length=50, validators=[cadastro.validator.validate_nome]),
        ),
    ]
