# Generated by Django 5.0.4 on 2024-05-19 01:56

import cadastro.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_alter_usuario_externo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_externo',
            name='cpf',
            field=models.CharField(max_length=11, validators=[cadastro.validator.validate_cpf]),
        ),
    ]
