# Generated by Django 5.0.4 on 2024-05-19 02:34

import cadastro.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_alter_usuario_externo_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_externo',
            name='responsavel_cpf',
            field=models.DateField(blank=True, max_length=11, null=True, validators=[cadastro.validator.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='usuario_externo',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[cadastro.validator.validate_nome]),
        ),
        migrations.AlterField(
            model_name='usuario_externo',
            name='telefone',
            field=models.CharField(max_length=14, validators=[cadastro.validator.validate_cpf]),
        ),
    ]
