# Generated by Django 5.0.4 on 2024-05-19 02:35

import cadastro.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_alter_usuario_externo_responsavel_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_externo',
            name='telefone',
            field=models.CharField(max_length=15, validators=[cadastro.validator.validate_cpf]),
        ),
    ]
