# Generated by Django 5.0.4 on 2024-05-19 02:37

import cadastro.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0015_alter_usuario_externo_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_externo',
            name='cpf',
            field=models.CharField(max_length=14, validators=[cadastro.validator.validate_cpf]),
        ),
    ]
