# Generated by Django 5.0.3 on 2024-05-22 19:27

import cadastro.validator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0017_alter_usuario_externo_responsavel_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='hora_atividade',
            field=models.TimeField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='nome_atividade',
            field=models.CharField(max_length=50, validators=[cadastro.validator.validate_nome]),
        ),
        migrations.AlterField(
            model_name='usuario_externo',
            name='responsavel_cpf',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[cadastro.validator.validate_cpf]),
        ),
        migrations.AddField(
            model_name='atividade',
            name='dia_atividade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.diaatividade'),
        ),
    ]
