# Generated by Django 5.0.4 on 2024-05-19 02:44

import cadastro.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0017_alter_usuario_externo_responsavel_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_externo',
            name='responsavel_cpf',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[cadastro.validator.validate_cpf]),
        ),
    ]
