# Generated by Django 5.0.4 on 2024-05-21 00:38

import cadastro.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0018_alter_usuario_externo_responsavel_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='nome_atividade',
            field=models.CharField(max_length=50, validators=[cadastro.validator.validate_nome]),
        ),
    ]
