# Generated by Django 5.0.4 on 2024-05-21 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0019_alter_atividade_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='hora_atividade',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='dia_atividade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.diaatividade'),
        ),
    ]
