# Generated by Django 5.0.3 on 2024-05-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0020_diaatividade_atividade_hora_atividade_and_more'),
    ]

    operations = [
    ]
