# Generated by Django 5.0.3 on 2024-05-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0021_merge_20240522_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='hora_atividade',
            field=models.TimeField(),
        ),
    ]
