# Generated by Django 5.0.4 on 2024-05-25 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0022_alter_atividade_hora_atividade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscrever_na_atividade',
            old_name='atividade',
            new_name='Responsavel',
        ),
    ]
