# Generated by Django 5.0.4 on 2024-05-25 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0023_rename_atividade_inscrever_na_atividade_responsavel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscrever_na_atividade',
            old_name='Responsavel',
            new_name='responsavel',
        ),
    ]
