# Generated by Django 5.0.4 on 2024-05-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0024_rename_responsavel_inscrever_na_atividade_responsavel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscrever_na_atividade',
            old_name='responsavel',
            new_name='atividade',
        ),
    ]
