# Generated by Django 5.0.4 on 2024-05-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0025_rename_responsavel_inscrever_na_atividade_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='inscricoes_feitas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atividade',
            name='limite_inscricoes',
            field=models.IntegerField(default=40),
        ),
    ]
