# Generated by Django 5.0.4 on 2024-05-26 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0026_atividade_inscricoes_feitas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='inscricoes_feitas',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='limite_inscricoes',
        ),
    ]
